export const colors = [
  "Black",
  "Blue",
  "Brown",
  "Gold",
  "Gray",
  "Green",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "Silver",
  "Violet",
  "White",
  "Yellow",
];

export const countries = [
  { currency: { code: "DZD" }, name: "Algeria" },
  { currency: { code: "BHD" }, name: "Bahrain" },
  { currency: { code: "EGP" }, name: "Egypt" },
  { currency: { code: "IRR" }, name: "Iran" },
  { currency: { code: "IQD" }, name: "Iraq" },
  { currency: { code: "JOD" }, name: "Jordan" },
  { currency: { code: "SAR" }, name: "Kingdom of Saudi Arabia" },
  { currency: { code: "KWD" }, name: "Kuwait" },
  { currency: { code: "LBP" }, name: "Lebanon" },
  { currency: { code: "LYD" }, name: "Libya" },
  { currency: { code: "MAD" }, name: "Morocco" },
  { currency: { code: "OMR" }, name: "Oman" },
  { currency: { code: "USD" }, name: "Palestine" },
  { currency: { code: "QAR" }, name: "Qatar" },
  { currency: { code: "SDG" }, name: "Sudan" },
  { currency: { code: "SYP" }, name: "Syria" },
  { currency: { code: "TND" }, name: "Tunisia" },
  { currency: { code: "AED" }, name: "United Arab Emirates" },
  { currency: { code: "YER" }, name: "Yemen" },
];
